# Git
alias gcm="git commit -m"
alias gcood="git checkout origin/dev"
alias gcoodp="git checkout origin/develop"
alias gcoom="git checkout origin/master"
alias gcoud="git checkout upstream/dev"
alias gcoudp="git checkout upstream/develop"
alias gcoum="git checkout upstream/master"
alias grbod="git rebase origin/dev"
alias grbodp="git rebase origin/develop"
alias grbom="git rebase origin/master"
alias grbud="git rebase upstream/dev"
alias grbudp="git rebase upstream/develop"
alias grbum="git rebase upstream/master"
alias grbsod="GIT_SEQUENCE_EDITOR=touch git rebase -i --autosquash origin/dev"
alias grbsodp="GIT_SEQUENCE_EDITOR=touch git rebase -i --autosquash origin/develop"
alias grbsom="GIT_SEQUENCE_EDITOR=touch git rebase -i --autosquash origin/master"
alias grbsud="GIT_SEQUENCE_EDITOR=touch git rebase -i --autosquash upstream/dev"
alias grbsudp="GIT_SEQUENCE_EDITOR=touch git rebase -i --autosquash upstream/develop"
alias grbsum="GIT_SEQUENCE_EDITOR=touch git rebase -i --autosquash upstream/master"
alias gff="gf origin && gf upstream && gf origin --no-prune"

# Docker
alias dcub="docker-compose up --build"
